### ISSUE TITLE
Valuesets in two repos

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-dcc-development/ehn-dcc-valuesets#5]
Shouldn't the valuesets represented in the schema repo be removed so that we don't risk getting the two repos out of sync?

**Comment by kruzikh** [comment]
I agree, we should remove it. @gabywh is there any content (like issues) that should be preserv ed?

**Comment by gabywh** [comment]
It will be removed should there be a future release of the DCC Schema. It will stay on all the release branches as this is how the repository was at the time of the release.

We could possibly remove it from main, but the default view is the latest current release and that is what people will see and these are fixed as per the release.

Repos getting out of sync: there shouldn't be much - if any - of a sync between them in the first place. The DCC Schema has by design only a weak reference to the valuesets.

The fact that the valuesets were in the DCC Schema repo at all was - like so many other things in these projects - simply a temporary measure at the time as they had nowhere else to go. A temporary measure that then all too quickly becomes seen in people's eyes as * the * way to do something, where the temporary nature of it is all too quickly forgotten.

At that time, I was waiting on the supposed eHN hosting for the DCC Schema repo to split the valuesets from the DCC Schema per se. As you may have gathered, at some point I stopped waiting for the eHN hosting and just split the valuesets out anyway (post 1.3.0 release seemed like a rather opportune moment to split them out).

**Comment by kruzikh** [comment]
Ok @gabywh, can you add a readme file into the old value set repository to navigate users to the right location? Something like THIS REPOSITORY is DEPRECATED go to ... !!!  :-)
Best
Hynek

**Comment by gabywh** [comment]
> Ok @gabywh, can you add a readme file into the old value set repository to navigate users to the right location? 

Was already planned for once I remove the valuesets - but only on main, not on any existing release branches.
Once again: this means that for any standard user just browsing the repository that - currently - release/1.3.0 is viewed and these changes (inclusive of any README.md changes)  will not be visible. You would need to either (1) consciously switch to main, or (2) wait for a new formal DCC Schema release, at which point the new release branch will be the default view.

> Something like THIS REPOSITORY is DEPRECATED go to ... !!! :-)

Which is most definitely untrue and rather misleading. This repository is definitely NOT deprecated. In fact it is _the_ authoritative repository for the DCC Schema. See for example page 4 in https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf, subsection "JSON Schema location and versions" which states 
> The authoritative official JSON schema for EUDCC is located at https://github.com/ehn-dccdevelopment/ehn-dcc-schema. Other locations are not authoritative 

I suspect you are conflating the valuesets (which shouldn't have even really been here in this repo, was a temporary solution) with the DCC Schema. This repository is the DCC Schema, which temporarily hosted the valuesets until they got a place of their own to live.

So yes, the valuesets will be removed from main, but not from any already released branch and a note in a new valuesets.md pointing to the correct location. Timescale: it just needs to be done before a new DCC Schema release - currently none planned.
